### ISSUE TITLE
CRCTP dataset unavailable

### ISSUE THREAD

**Issue by Netz00** [christianabbet/SRA#2]
Inside [paper](https://www.sciencedirect.com/science/article/pii/S136184152030061X) is stated following: _Data will be made available on request._ ([Download data](https://ars.els-cdn.com/content/image/1-s2.0-S136184152030061X-mmc1.xml))

Inside [table ](https://github.com/christianabbet/SRA/blob/main/README.md#step-1-download-publicly-available-data-source) CRCTP [download](https://warwick.ac.uk/fac/cross_fac/tia/data/crc-tp) opens the login page.

Download CRCTP training/test data doesn't work
`wget -O fold2.zip https://warwick.ac.uk/fac/cross_fac/tia/data/crc-tp/fold2.zip`

As of the time of writing this issue, the data is not publicly available. Therefore I propose adding a warning note in the README for future repository visitors.

**Comment by christianabbet** [comment]
Thank you for the info. The README file was updated accordingly!
