### ISSUE TITLE
can I use this model for gastric cancer prediction?

### ISSUE THREAD

**Issue by mzhoufulai** [christianabbet/SRA#3]
Hello,
    I am wondering whether it is appropriate to apply this model (Kather19 + CRCTP) for predicting gastric cancer cases.  Alternatively, is it possible to use the Kather19 dataset as source and our gastric cancer dataset as target to train a model for predicting gastric cancer cases?

Thanks

**Comment by christianabbet** [comment]
Hi,

I think the transfer is tricky. The best would be to discuss it with a pathologist. There might be some overlap in terms of epithelial tissue for example. However, the classes examples are restricted to colorectal cases.
